# Generated by Django 5.2.7 on 2025-11-02 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoReferencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mongodb_object_id', models.CharField(max_length=255, unique=True)),
                ('nombre_archivo', models.TextField()),
                ('tipo_documento', models.CharField(choices=[('EPICRISIS_PDF', 'Epicrisis PDF'), ('REPORTE_EXCEL', 'Reporte Excel'), ('OTRO', 'Otro')], db_index=True, max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referencia de Documento',
                'verbose_name_plural': 'Referencias de Documentos',
                'db_table': 'DocumentoReferencia',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_parto', models.DateTimeField()),
                ('edad_gestacional', models.IntegerField(blank=True, null=True)),
                ('tipo_parto', models.CharField(choices=[('Eutócico', 'Eutócico'), ('Cesárea Electiva', 'Cesárea Electiva'), ('Cesárea Urgencia', 'Cesárea Urgencia'), ('Fórceps', 'Fórceps'), ('Ventosa', 'Ventosa')], max_length=50)),
                ('anestesia', models.CharField(blank=True, choices=[('Epidural', 'Epidural'), ('Raquídea', 'Raquídea'), ('General', 'General'), ('Otra', 'Otra'), ('Ninguna', 'Ninguna')], max_length=50, null=True)),
                ('partograma_data', models.JSONField(blank=True, null=True)),
                ('epicrisis_data', models.JSONField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'Parto',
                'ordering': ['-fecha_parto'],
            },
        ),
        migrations.CreateModel(
            name='PartoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Parto-Diagnóstico',
                'verbose_name_plural': 'Partos-Diagnósticos',
                'db_table': 'PartoDiagnostico',
            },
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut_provisorio', models.TextField(blank=True, null=True)),
                ('estado_al_nacer', models.CharField(choices=[('Vivo', 'Vivo'), ('Nacido Muerto', 'Nacido Muerto')], max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Indeterminado', 'Indeterminado')], max_length=50, null=True)),
                ('peso_gramos', models.IntegerField(blank=True, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('apgar_1_min', models.SmallIntegerField(blank=True, null=True)),
                ('apgar_5_min', models.SmallIntegerField(blank=True, null=True)),
                ('profilaxis_vit_k', models.BooleanField(blank=True, null=True)),
                ('profilaxis_oftalmica', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'db_table': 'RecienNacido',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Defuncion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_defuncion', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('causa_defuncion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defunciones', to='catalogos.diagnosticocie10')),
                ('madre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defuncion', to='pacientes.madre')),
            ],
            options={
                'verbose_name': 'Defunción',
                'verbose_name_plural': 'Defunciones',
                'db_table': 'Defuncion',
                'ordering': ['-fecha_defuncion'],
            },
        ),
    ]
