# Generated by Django 5.2.7 on 2025-11-02 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('partos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defuncion',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defunciones_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoreferencia',
            name='usuario_generacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_generados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parto',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='pacientes.madre'),
        ),
        migrations.AddField(
            model_name='parto',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoreferencia',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_referencia', to='partos.parto'),
        ),
        migrations.AddField(
            model_name='partodiagnostico',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.diagnosticocie10'),
        ),
        migrations.AddField(
            model_name='partodiagnostico',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partos.parto'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partos.parto'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recien_nacidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defuncion',
            name='recien_nacido',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defuncion', to='partos.reciennacido'),
        ),
        migrations.AlterUniqueTogether(
            name='partodiagnostico',
            unique_together={('parto', 'diagnostico')},
        ),
        migrations.AddConstraint(
            model_name='defuncion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recien_nacido__isnull', False), ('madre__isnull', True)), models.Q(('recien_nacido__isnull', True), ('madre__isnull', False)), _connector='OR'), name='check_recien_nacido_or_madre'),
        ),
    ]
