# Generated by Django 5.2.7 on 2025-11-02 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rut_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('nombre_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('telefono_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('rut_encrypted', models.TextField(blank=True, null=True)),
                ('nombre_encrypted', models.TextField(blank=True, null=True)),
                ('telefono_encrypted', models.TextField(blank=True, null=True)),
                ('antecedentes_medicos', models.TextField(blank=True, null=True)),
                ('ficha_clinica_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('pertenece_pueblo_originario', models.BooleanField(default=False)),
                ('prevision', models.CharField(blank=True, choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'PARTICULAR'), ('NINGUNA', 'NINGUNA')], max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Madre',
                'verbose_name_plural': 'Madres',
                'db_table': 'Madre',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
