# Generated by Django 5.2.7 on 2025-11-02 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoCIE10',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE-10',
                'verbose_name_plural': 'Diagnósticos CIE-10',
                'db_table': 'DiagnosticoCIE10',
                'ordering': ['codigo'],
            },
        ),
    ]
