# Generated by Django 5.2.7 on 2025-11-02 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(db_index=True, max_length=255)),
                ('tabla_afectada', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('registro_id_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('ip_usuario', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'LogAuditoria',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
